default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['db_host'] || :localhost %>
  port: <%= ENV['db_port'] || 5432 %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  user: <%= ENV['db_user'] || :postgres %>
  password: <%= ENV['db_password'] || :monkeflip %>

development:
  <<: *default
  database: recipe_api_dev

test:
  <<: *default
  database: recipe_api_test

production:
  <<: *default
  database: recipe_api_prod
